### ISSUE TITLE
Build Failure for 1.1 on Mac OS X

### ISSUE THREAD

**Issue by ahagenbruch** [agazzarini/SolRDF#119]
When building SolRDF on Mac OS 10.9.5 (Java 1.8.0_65, Maven 3.3.3) I get:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project solrdf-core: Compilation failure
[ERROR] /home/someuser/tmp/solrdf-download/solrdf/solrdf-core/src/main/java/org/gazzax/labs/solrdf/search/component/PagedResultSet.java:[13,71] package com.sun.tools.internal.xjc.generator.bean.ImplStructureStrategy does not exist

**Comment by agazzarini** [comment]
Hi @ahagenbruch my fault, I inserted a comment in a method with a wrong reference to the Result class (and the IDE automatically imported that class). 

I removed that, so now it should work. I say "should" because I don't have MAC OS so please keep me informed and I will (hopefully) close the issue

**Comment by ahagenbruch** [comment]
Yep, that must have been it. Everything's ok now. Thanks a lot (again) for your quick response...
